# Generated by Django 4.2.4 on 2023-12-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_review_id_remove_review_review_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='review_user',
        ),
    ]
